apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: quay.io/dsanchor/quarkus-petclinic
  newName: image-registry.openshift-image-registry.svc.cluster.local:5000/user0/quarkus-petclinic
  newTag: 12b08f69e5fc30bb38e9dab3fc1d8a339528bcbb
